export const OPEN_NAV_SIDEBAR= 'OPEN_NAV_SIDEBAR';
export const CLOSE_NAV_SIDEBAR= 'CLOSE_NAV_SIDEBAR';
export const GET_PRODUCTS_BEGIN= 'GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS= 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR= 'GET_PRODUCTS_ERROR';
